spring.application.name=FleetManagementAPI

spring.profiles.active=local

spring.jpa.open-in-view=false

# ----------------------------------------
# JWT Defaults
# ----------------------------------------

jwt.expiration=3600000
